apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test
  region: eu-west-2

nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 4
    minSize: 1
    maxSize: 4
    volumeSize: 50
    volumeType: gp2
    availabilityZones: ["eu-west-2a", "eu-west-2b", "eu-west-2c"]
    labels:
      nodegroup-type: worker
